# Generated by Django 5.1.5 on 2025-01-31 14:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("parking_reservation", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ParkingReservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("parkingNo", models.IntegerField()),
                ("name", models.CharField(max_length=100)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "day_division",
                    models.CharField(
                        choices=[("AM", "AM"), ("PM", "PM"), ("終日", "終日")],
                        default="終日",
                        max_length=10,
                    ),
                ),
            ],
        ),
    ]
