# Generated by Django 5.1.5 on 2025-02-01 10:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("parking_reservation", "0002_parkingreservation"),
    ]

    operations = [
        migrations.RenameField(
            model_name="parkingreservation",
            old_name="name",
            new_name="reservation_holder",
        ),
    ]
