# Generated by Django 5.1.5 on 2025-02-08 14:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "parking_reservation",
            "0003_rename_name_parkingreservation_reservation_holder",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="parkingreservation",
            old_name="parkingNo",
            new_name="parking_no",
        ),
    ]
