# Generated by Django 5.1.5 on 2025-03-25 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_reservation', '0004_rename_parkingno_parkingreservation_parking_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingFeeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parking_fee', models.IntegerField()),
            ],
        ),
    ]
