# Generated by Django 5.1.5 on 2025-06-21 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_reservation', '0006_remove_parkingreservation_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingreservation',
            name='date',
            field=models.DateField(default='2025-06-21'),
            preserve_default=False,
        ),
    ]
